// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg33j42JjEpf-70AG2isKln_QkJjDa_v8',
    appId: '1:194326811955:web:a94d5572b571f8aa9f1a46',
    messagingSenderId: '194326811955',
    projectId: 'realestate-d9b12',
    authDomain: 'realestate-d9b12.firebaseapp.com',
    storageBucket: 'realestate-d9b12.appspot.com',
    measurementId: 'G-E69GJC1L1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClA90xeElp5-gYxidlZ2oHYu90uGjwnxo',
    appId: '1:194326811955:android:edadc285e2235d529f1a46',
    messagingSenderId: '194326811955',
    projectId: 'realestate-d9b12',
    storageBucket: 'realestate-d9b12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrQRIdqFjFgUtcJJYQILmUMtR7y4J4uJo',
    appId: '1:194326811955:ios:ad09d18b14ff0b949f1a46',
    messagingSenderId: '194326811955',
    projectId: 'realestate-d9b12',
    storageBucket: 'realestate-d9b12.appspot.com',
    androidClientId: '194326811955-caks2beij0egr2mj1gfqj46bv3l8pu46.apps.googleusercontent.com',
    iosClientId: '194326811955-a2istl019eupsdqiond2lb0e6u8aq5jj.apps.googleusercontent.com',
    iosBundleId: 'com.example.realestate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrQRIdqFjFgUtcJJYQILmUMtR7y4J4uJo',
    appId: '1:194326811955:ios:d3ba7862d148a62b9f1a46',
    messagingSenderId: '194326811955',
    projectId: 'realestate-d9b12',
    storageBucket: 'realestate-d9b12.appspot.com',
    androidClientId: '194326811955-caks2beij0egr2mj1gfqj46bv3l8pu46.apps.googleusercontent.com',
    iosClientId: '194326811955-ebg1mti82t6sf4pv6up9mqa2fumkrtm2.apps.googleusercontent.com',
    iosBundleId: 'com.example.realestate.RunnerTests',
  );
}
