// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSwUrQ_dDAWlINl0sWLsU04dEdHG2NaO8',
    appId: '1:714414033482:web:ac7e73f73bcba36199b4b3',
    messagingSenderId: '714414033482',
    projectId: 'realestate-14af5',
    authDomain: 'realestate-14af5.firebaseapp.com',
    storageBucket: 'realestate-14af5.appspot.com',
    measurementId: 'G-MVPJNCDB4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMz6ZUNhpinxe7LIDIeH8KwHPV5jmLuUY',
    appId: '1:714414033482:android:43b859932a45c07d99b4b3',
    messagingSenderId: '714414033482',
    projectId: 'realestate-14af5',
    storageBucket: 'realestate-14af5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8TrLOC9Zr1meWQa8fjfjLgJ1LyVxrJQk',
    appId: '1:714414033482:ios:bc250e71327397d099b4b3',
    messagingSenderId: '714414033482',
    projectId: 'realestate-14af5',
    storageBucket: 'realestate-14af5.appspot.com',
    iosBundleId: 'com.example.realestate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8TrLOC9Zr1meWQa8fjfjLgJ1LyVxrJQk',
    appId: '1:714414033482:ios:3370e5963912b4a099b4b3',
    messagingSenderId: '714414033482',
    projectId: 'realestate-14af5',
    storageBucket: 'realestate-14af5.appspot.com',
    iosBundleId: 'com.example.realestate.RunnerTests',
  );
}
